#!/bin/bash
# Phase 2 & Phase 3 Code Quality Fixes for Farmv2
# Generated by Claude Code Review
# Copy-paste this entire script into your Replit shell

set -e

echo "========================================="
echo "Applying Phase 2 & Phase 3 Fixes to Farmv2"
echo "========================================="

# Navigate to Farmv2 directory
cd /home/user/Farmv2

# ============================================
# PHASE 2: STABILITY & SAFETY FIXES
# ============================================

echo ""
echo "[Phase 2.1] Configuring database pool with proper timeouts..."

# Fix 1: Database pool configuration - add timeouts and connection limits
cat > /tmp/routes_pool_fix.py << 'POOL_FIX_EOF'
async def get_pool() -> asyncpg.Pool:
    global _db_pool
    if _db_pool is None:
        db_url = get_db_url()
        _db_pool = await asyncpg.create_pool(
            db_url,
            min_size=1,
            max_size=20,
            command_timeout=60.0,
            max_inactive_connection_lifetime=300.0
        )
    return _db_pool
POOL_FIX_EOF

# Apply database pool fix
python3 << 'PYTHON_EOF'
with open('src/api/routes.py', 'r') as f:
    content = f.read()

old_pool = '''async def get_pool() -> asyncpg.Pool:
    global _db_pool
    if _db_pool is None:
        db_url = get_db_url()
        _db_pool = await asyncpg.create_pool(db_url, min_size=1, max_size=10)
    return _db_pool'''

new_pool = '''async def get_pool() -> asyncpg.Pool:
    global _db_pool
    if _db_pool is None:
        db_url = get_db_url()
        _db_pool = await asyncpg.create_pool(
            db_url,
            min_size=1,
            max_size=20,
            command_timeout=60.0,
            max_inactive_connection_lifetime=300.0
        )
    return _db_pool'''

content = content.replace(old_pool, new_pool)

with open('src/api/routes.py', 'w') as f:
    f.write(content)
print("✓ Database pool configuration updated")
PYTHON_EOF

echo "[Phase 2.2] Replacing print() with proper logging..."

# Fix 2: Replace print() statements with logging
python3 << 'PYTHON_EOF'
with open('src/api/routes.py', 'r') as f:
    content = f.read()

# Add logging import if not present
if 'import logging' not in content:
    # Add after other imports at the top
    content = content.replace('from collections import defaultdict', 'from collections import defaultdict\nimport logging')

# Replace report_db_provider function
old_report = '''def report_db_provider():
    """Log which DB provider is being used at startup."""
    supabase_url = os.environ.get("SUPABASE_DB_URL", "")
    database_url = os.environ.get("DATABASE_URL", "")

    if supabase_url:
        print("[DB] Using SUPABASE_DB_URL (Supabase Postgres)")
    elif database_url:
        if "replit" in database_url.lower() or "neon" in database_url.lower():
            print("[DB] Using DATABASE_URL (Replit/Neon Postgres)")
        else:
            print("[DB] Using DATABASE_URL (external Postgres)")
    else:
        print("[DB] WARNING: No database URL configured!")'''

new_report = '''def report_db_provider():
    """Log which DB provider is being used at startup."""
    logger = logging.getLogger(__name__)
    supabase_url = os.environ.get("SUPABASE_DB_URL", "")
    database_url = os.environ.get("DATABASE_URL", "")

    if supabase_url:
        logger.info("[DB] Using SUPABASE_DB_URL (Supabase Postgres)")
    elif database_url:
        if "replit" in database_url.lower() or "neon" in database_url.lower():
            logger.info("[DB] Using DATABASE_URL (Replit/Neon Postgres)")
        else:
            logger.info("[DB] Using DATABASE_URL (external Postgres)")
    else:
        logger.warning("[DB] WARNING: No database URL configured!")'''

content = content.replace(old_report, new_report)

# Replace debug_reconcile_raw print statements
content = content.replace(
    '''    print(f"[DEBUG-RAW] Raw aod_lists keys: {list(aod_lists.keys())}")
    print(f"[DEBUG-RAW] actual_reason_codes present: {'actual_reason_codes' in aod_lists}")
    print(f"[DEBUG-RAW] actual_reason_codes value: {aod_lists.get('actual_reason_codes', 'NOT_FOUND')}")''',
    '''    logger = logging.getLogger(__name__)
    logger.debug(f"[DEBUG-RAW] Raw aod_lists keys: {list(aod_lists.keys())}")
    logger.debug(f"[DEBUG-RAW] actual_reason_codes present: {'actual_reason_codes' in aod_lists}")
    logger.debug(f"[DEBUG-RAW] actual_reason_codes value: {aod_lists.get('actual_reason_codes', 'NOT_FOUND')}")'''
)

# Replace create_reconciliation print statements
content = content.replace(
    '''    print(f"[DEBUG] Raw request aod_lists keys: {list(raw_aod_lists.keys())}")
    print(f"[DEBUG] Raw actual_reason_codes: {list(raw_aod_lists.get('actual_reason_codes', {}).keys())[:5]}")''',
    '''    logger = logging.getLogger(__name__)
    logger.debug(f"[DEBUG] Raw request aod_lists keys: {list(raw_aod_lists.keys())}")
    logger.debug(f"[DEBUG] Raw actual_reason_codes: {list(raw_aod_lists.get('actual_reason_codes', {}).keys())[:5]}")'''
)

with open('src/api/routes.py', 'w') as f:
    f.write(content)
print("✓ Replaced print() statements with logging")
PYTHON_EOF

echo "[Phase 2.3] Adding offset parameter for pagination..."

# Fix 3: Add offset parameter to list_snapshots endpoint
python3 << 'PYTHON_EOF'
with open('src/api/routes.py', 'r') as f:
    content = f.read()

old_pagination = '''@router.get("/api/snapshots", response_model=list[SnapshotMetadata])
async def list_snapshots(
    tenant_id: Optional[str] = Query(None, description="Filter by tenant ID"),
    limit: int = Query(100, ge=1, le=1000, description="Maximum number of results")
):
    pool = await get_pool()

    async with pool.acquire() as conn:
        if tenant_id:
            rows = await conn.fetch(
                "SELECT snapshot_id, snapshot_fingerprint, tenant_id, seed, scale, enterprise_profile, realism_profile, created_at, schema_version FROM snapshots WHERE tenant_id = $1 ORDER BY created_at DESC LIMIT $2",
                tenant_id, limit
            )
        else:
            rows = await conn.fetch(
                "SELECT snapshot_id, snapshot_fingerprint, tenant_id, seed, scale, enterprise_profile, realism_profile, created_at, schema_version FROM snapshots ORDER BY created_at DESC LIMIT $1",
                limit
            )'''

new_pagination = '''@router.get("/api/snapshots", response_model=list[SnapshotMetadata])
async def list_snapshots(
    tenant_id: Optional[str] = Query(None, description="Filter by tenant ID"),
    limit: int = Query(100, ge=1, le=1000, description="Maximum number of results"),
    offset: int = Query(0, ge=0, description="Number of results to skip")
):
    pool = await get_pool()

    async with pool.acquire() as conn:
        if tenant_id:
            rows = await conn.fetch(
                "SELECT snapshot_id, snapshot_fingerprint, tenant_id, seed, scale, enterprise_profile, realism_profile, created_at, schema_version FROM snapshots WHERE tenant_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3",
                tenant_id, limit, offset
            )
        else:
            rows = await conn.fetch(
                "SELECT snapshot_id, snapshot_fingerprint, tenant_id, seed, scale, enterprise_profile, realism_profile, created_at, schema_version FROM snapshots ORDER BY created_at DESC LIMIT $1 OFFSET $2",
                limit, offset
            )'''

content = content.replace(old_pagination, new_pagination)

with open('src/api/routes.py', 'w') as f:
    f.write(content)
print("✓ Added offset parameter for pagination")
PYTHON_EOF

echo "[Phase 2.4] Extracting duplicate AOD HTTP client code..."

# Fix 4: Create reusable HTTP client helper in aod_client.py
python3 << 'PYTHON_EOF'
with open('src/services/aod_client.py', 'r') as f:
    content = f.read()

# Add helper function before clear_cache()
helper_function = '''

async def create_aod_http_client(timeout: float = 30.0) -> tuple[httpx.AsyncClient, dict]:
    """Create configured HTTP client for AOD with auth headers.

    Returns:
        tuple: (AsyncClient instance, headers dict with auth if configured)

    Usage:
        async with create_aod_http_client() as (client, headers):
            resp = await client.get(url, headers=headers)
    """
    aod_secret = os.environ.get("AOD_SHARED_SECRET", "")
    headers = {}
    if aod_secret:
        headers["Authorization"] = f"Bearer {aod_secret}"

    client = httpx.AsyncClient(timeout=timeout, follow_redirects=True)
    return client, headers


'''

# Insert before clear_cache() function
content = content.replace('def clear_cache():', helper_function + 'def clear_cache():')

with open('src/services/aod_client.py', 'w') as f:
    f.write(content)
print("✓ Added reusable AOD HTTP client helper")
PYTHON_EOF

# ============================================
# PHASE 3: QUALITY IMPROVEMENTS
# ============================================

echo ""
echo "[Phase 3.1] Adding ReconciliationMode enum..."

# Fix 5: Add ReconciliationMode enum to models
python3 << 'PYTHON_EOF'
with open('src/models/planes.py', 'r') as f:
    content = f.read()

# Add enum after DataPresetEnum
enum_addition = '''

class ReconciliationModeEnum(str, Enum):
    sprawl = "sprawl"  # External SaaS domains only (shadow IT detection)
    infra = "infra"    # Internal services only (infrastructure sprawl)
    all = "all"        # All assets regardless of type
'''

# Insert after DataPresetEnum
content = content.replace(
    'class DataPresetEnum(str, Enum):\n    clean_baseline = "clean_baseline"\n    enterprise_mess = "enterprise_mess"\n    adversarial = "adversarial"',
    'class DataPresetEnum(str, Enum):\n    clean_baseline = "clean_baseline"\n    enterprise_mess = "enterprise_mess"\n    adversarial = "adversarial"' + enum_addition
)

# Update ReconcileRequest to use enum
content = content.replace(
    '    mode: str = "sprawl"  # sprawl (default), infra, or all',
    '    mode: ReconciliationModeEnum = ReconciliationModeEnum.sprawl'
)

with open('src/models/planes.py', 'w') as f:
    f.write(content)
print("✓ Added ReconciliationModeEnum")
PYTHON_EOF

echo "[Phase 3.2] Fixing timestamp parsing with python-dateutil..."

# Fix 6: Add python-dateutil dependency
python3 << 'PYTHON_EOF'
with open('pyproject.toml', 'r') as f:
    content = f.read()

if 'python-dateutil' not in content:
    # Add python-dateutil to dependencies
    content = content.replace(
        '    "pydantic>=2.12.5",',
        '    "pydantic>=2.12.5",\n    "python-dateutil>=2.9.0",'
    )

    with open('pyproject.toml', 'w') as f:
        f.write(content)
    print("✓ Added python-dateutil to dependencies")
else:
    print("✓ python-dateutil already in dependencies")
PYTHON_EOF

# Update reconciliation.py to use dateutil
python3 << 'PYTHON_EOF'
with open('src/services/reconciliation.py', 'r') as f:
    content = f.read()

# Add dateutil import
if 'from dateutil' not in content:
    content = content.replace(
        'from datetime import datetime',
        'from datetime import datetime\nfrom dateutil import parser as dateutil_parser'
    )

# Replace parse_timestamp function
old_parse = '''def parse_timestamp(ts: Optional[str]) -> Optional[datetime]:
    """Parse ISO timestamp string to datetime.

    Handles timezone suffixes and returns naive datetime for comparison.
    """
    if not ts:
        return None
    try:
        ts = ts.replace('Z', '+00:00')
        if '+' in ts:
            ts = ts.split('+')[0]
        return datetime.fromisoformat(ts)
    except (ValueError, TypeError, AttributeError) as e:
        # Log warning but don't fail - return None for invalid timestamps
        trace_log("reconciliation", "parse_timestamp_error", {
            "timestamp": ts,
            "error": str(e)
        })
        return None'''

new_parse = '''def parse_timestamp(ts: Optional[str]) -> Optional[datetime]:
    """Parse ISO timestamp string to datetime using dateutil.

    Handles various timestamp formats and timezones, returns naive datetime for comparison.
    """
    if not ts:
        return None
    try:
        # dateutil.parser handles ISO8601, RFC3339, and many other formats
        dt = dateutil_parser.parse(ts)
        # Convert to naive datetime (strip timezone for comparison)
        return dt.replace(tzinfo=None) if dt.tzinfo else dt
    except (ValueError, TypeError, AttributeError) as e:
        # Log warning but don't fail - return None for invalid timestamps
        trace_log("reconciliation", "parse_timestamp_error", {
            "timestamp": ts,
            "error": str(e)
        })
        return None'''

content = content.replace(old_parse, new_parse)

with open('src/services/reconciliation.py', 'w') as f:
    f.write(content)
print("✓ Updated timestamp parsing to use python-dateutil")
PYTHON_EOF

echo "[Phase 3.3] Improving string matching logic to avoid false positives..."

# Fix 7: Improve substring matching with length checks
python3 << 'PYTHON_EOF'
with open('src/services/reconciliation.py', 'r') as f:
    lines = f.readlines()

output = []
for i, line in enumerate(lines):
    # Fix cloud resource substring matching (around line 228)
    if 'if any(n in name or name in n for n in normalized_names):' in line:
        indent = len(line) - len(line.lstrip())
        output.append(' ' * indent + '# Substring match with length check to avoid false positives (e.g., "aws" matching "awsome")\n')
        output.append(' ' * indent + 'if any((len(n) > 3 and len(name) > 3 and (n in name or name in n)) for n in normalized_names):\n')
        continue

    # Fix vendor substring matching in contracts (around line 245)
    if 'if vendor in key or key in vendor:' in line and 'for key in name_to_keys.keys():' in lines[i-1]:
        indent = len(line) - len(line.lstrip())
        output.append(' ' * indent + '# Substring match with length check\n')
        output.append(' ' * indent + 'if len(vendor) > 3 and len(key) > 3 and (vendor in key or key in vendor):\n')
        continue

    # Fix product substring matching (around line 252)
    if 'if product in key or key in product:' in line and 'for key in name_to_keys.keys():' in lines[i-1]:
        indent = len(line) - len(line.lstrip())
        output.append(' ' * indent + '# Substring match with length check\n')
        output.append(' ' * indent + 'if len(product) > 3 and len(key) > 3 and (product in key or key in product):\n')
        continue

    # Fix transaction vendor substring matching (around line 269)
    if 'if vendor in key or key in vendor:' in line and 'for key in name_to_keys.keys():' in lines[i-2:i]:
        indent = len(line) - len(line.lstrip())
        output.append(' ' * indent + '# Substring match with length check\n')
        output.append(' ' * indent + 'if len(vendor) > 3 and len(key) > 3 and (vendor in key or key in vendor):\n')
        continue

    output.append(line)

with open('src/services/reconciliation.py', 'w') as f:
    f.writelines(output)
print("✓ Improved substring matching with length checks")
PYTHON_EOF

echo "[Phase 3.4] Improving variable naming for readability..."

# Fix 8: Improve variable naming
python3 << 'PYTHON_EOF'
with open('src/services/reconciliation.py', 'r') as f:
    content = f.read()

# Replace obs -> observation
content = content.replace('for obs in observations:', 'for observation in observations:')
content = content.replace("obs.get('domain')", "observation.get('domain')")
content = content.replace("obs.get('observed_uri')", "observation.get('observed_uri')")
content = content.replace("obs.get('hostname')", "observation.get('hostname')")
content = content.replace("obs.get('observed_name'", "observation.get('observed_name'")
content = content.replace("obs.get('vendor_hint')", "observation.get('vendor_hint')")
content = content.replace("obs.get('observed_at')", "observation.get('observed_at')")
content = content.replace("obs.get('source'", "observation.get('source'")

# Replace ci -> config_item
content = content.replace('for ci in cmdb_cis:', 'for config_item in cmdb_cis:')
content = content.replace("ci.get('name'", "config_item.get('name'")
content = content.replace("ci.get('external_ref')", "config_item.get('external_ref')")
content = content.replace("ci.get('vendor')", "config_item.get('vendor')")
content = content.replace("ci.get('ci_id')", "config_item.get('ci_id')")
content = content.replace("ci.get('lifecycle')", "config_item.get('lifecycle')")
content = content.replace("ci.get('ci_type')", "config_item.get('ci_type')")
content = content.replace('ci_vendor = ', 'config_item_vendor = ')
content = content.replace('if ci_vendor:', 'if config_item_vendor:')
content = content.replace('vendor_to_keys.get(ci_vendor', 'vendor_to_keys.get(config_item_vendor')

# Replace cand -> candidate (in loops and assignments)
content = content.replace('for key, cand in candidates.items():', 'for key, candidate in candidates.items():')
content = content.replace("cand['", "candidate['")
content = content.replace('= candidates[key]\n', '= candidate_info\n')
content = content.replace("cand = candidates[key]", "candidate_info = candidates[key]")
content = content.replace("candidate_info['", "candidate_info['")

# Replace res -> resource
content = content.replace('for res in cloud_resources:', 'for resource in cloud_resources:')
content = content.replace("res.get('name'", "resource.get('name'")

with open('src/services/reconciliation.py', 'w') as f:
    f.write(content)
print("✓ Improved variable naming")
PYTHON_EOF

echo ""
echo "========================================="
echo "✓ All Phase 2 & Phase 3 fixes applied!"
echo "========================================="
echo ""
echo "Summary of changes:"
echo "Phase 2 (Stability & Safety):"
echo "  ✓ Database pool: Added timeouts and increased max_size to 20"
echo "  ✓ Logging: Replaced print() with proper logging.getLogger()"
echo "  ✓ Pagination: Added offset parameter to /api/snapshots"
echo "  ✓ HTTP client: Created reusable helper in aod_client.py"
echo ""
echo "Phase 3 (Quality Improvements):"
echo "  ✓ Enums: Added ReconciliationModeEnum for type safety"
echo "  ✓ Timestamps: Using python-dateutil for robust parsing"
echo "  ✓ String matching: Added length checks to prevent false positives"
echo "  ✓ Variable names: obs→observation, ci→config_item, cand→candidate, res→resource"
echo ""
echo "Next steps:"
echo "  1. Run: uv pip install -e ."
echo "  2. Test the application"
echo "  3. Review git diff to verify changes"
echo ""
